In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
import plotly.offline as py
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

import plotly.graph_objs as go

In [2]:
##Read data
data=pd.read_csv("bankadditionalfull.csv",sep=';')
data

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
10,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
11,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
12,29,blue-collar,single,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
13,57,housemaid,divorced,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
14,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
15,54,retired,married,basic.9y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
16,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
17,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
18,50,blue-collar,married,basic.9y,no,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
19,39,management,single,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
20,30,unemployed,married,high.school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
21,55,blue-collar,married,basic.4y,unknown,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
22,55,retired,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
23,41,technician,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
24,37,admin.,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
25,35,technician,married,university.degree,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
26,59,technician,married,unknown,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
27,39,self-employed,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
28,54,technician,single,university.degree,unknown,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
29,55,unknown,married,university.degree,unknown,unknown,unknown,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41158,35,technician,divorced,basic.4y,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.035,4963.6,yes
41159,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,1,9,4,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41160,33,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.035,4963.6,yes
41161,33,admin.,married,university.degree,no,yes,no,cellular,nov,tue,...,1,999,1,failure,-1.1,94.767,-50.8,1.035,4963.6,no
41162,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
41163,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,3,4,2,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41164,54,admin.,married,professional.course,no,no,no,cellular,nov,tue,...,2,10,1,success,-1.1,94.767,-50.8,1.035,4963.6,yes
41165,38,housemaid,divorced,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,yes
41166,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
41167,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41168,38,entrepreneur,married,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41169,62,services,married,high.school,no,yes,no,cellular,nov,wed,...,5,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
41170,40,management,divorced,university.degree,no,yes,no,cellular,nov,wed,...,2,999,4,failure,-1.1,94.767,-50.8,1.030,4963.6,no
41171,33,student,married,professional.course,no,yes,no,telephone,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,yes
41172,31,admin.,single,university.degree,no,yes,no,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,yes
41173,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94.767,-50.8,1.031,4963.6,yes
41174,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,1,6,success,-1.1,94.767,-50.8,1.031,4963.6,yes
41175,34,student,single,unknown,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94.767,-50.8,1.031,4963.6,no
41176,38,housemaid,divorced,high.school,no,yes,yes,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,no
41177,57,retired,married,professional.course,no,yes,no,cellular,nov,thu,...,6,999,0,nonexistent,-1.1,94.767,-50.8,1.031,4963.6,no
41178,62,retired,married,university.degree,no,no,no,cellular,nov,thu,...,2,6,3,success,-1.1,94.767,-50.8,1.031,4963.6,yes
41179,64,retired,divorced,professional.course,no,yes,no,cellular,nov,fri,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41180,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41181,37,admin.,married,university.degree,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41182,29,unemployed,single,basic.4y,no,yes,no,cellular,nov,fri,...,1,9,1,success,-1.1,94.767,-50.8,1.028,4963.6,no
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [24]:
##Dependant variable Y
trace1=go.Bar(
   x=list(data.y.unique()),
   y=[data[data.y=='yes'].y.count()],
   name='YES')

trace2=go.Bar(
   x=list(data.y.unique()),
   y=[data[data.y=='no'].y.count()],
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT CATEGORIES OF 'Y'",barmode='group',
                 xaxis=dict(title='Y',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [26]:
##Jobs
trace1=go.Bar(
   x=list(data.job.unique()),
   y=data[data.y=='yes'].job.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.job.unique()),
   y=data[data.y=='no'].job.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT CATEGORIES OF JOBS",barmode='group',
                 xaxis=dict(title='Jobs',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [36]:
##Marital
trace1=go.Bar(
   x=list(data.marital.unique()),
   y=data[data.y=='yes'].marital.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.marital.unique()),
   y=data[data.y=='no'].marital.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT CATEGORIES OF MARITAL STATUS",barmode='group',
                 xaxis=dict(title='Marital Status',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [35]:
##Education
trace1=go.Bar(
   x=list(data.education.unique()),
   y=data[data.y=='yes'].education.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.education.unique()),
   y=data[data.y=='no'].education.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT CATEGORIES OF EDUCATION LEVEL",barmode='group',
                 xaxis=dict(title='Education Level',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [32]:
##Credit Default
trace1=go.Bar(
   x=list(data.default.unique()),
   y=data[data.y=='yes'].default.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.default.unique()),
   y=data[data.y=='no'].default.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT CATEGORIES OF CREDIT DEFAULT",barmode='group',
                 xaxis=dict(title='Does the person have credit in default?',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [33]:
##Housing Loan
trace1=go.Bar(
   x=list(data.housing.unique()),
   y=data[data.y=='yes'].housing.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.housing.unique()),
   y=data[data.y=='no'].housing.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT POSSIBILITIES OF HOUSING LOAN",barmode='group',
                 xaxis=dict(title='Does the person have Housing Loan?',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [55]:
##Personal Loan
trace1=go.Bar(
   x=list(data.loan.unique()),
   y=data[data.y=='yes'].loan.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.loan.unique()),
   y=data[data.y=='no'].loan.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT POSSIBILITIES OF PERSONAL LOAN",barmode='group',
                 xaxis=dict(title='Does the person have Personal Loan?',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [38]:
##Previous Communication Type
trace1=go.Bar(
   x=list(data.contact.unique()),
   y=data[data.y=='yes'].contact.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.contact.unique()),
   y=data[data.y=='no'].contact.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT POSSIBILITIES OF PREVIOUS COMMUNICATION TYPE",
                 barmode='group',
                 xaxis=dict(title='Previous Communication type',
                            titlefont=dict(family='Calibri',size=16)),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [52]:
##Previous Contact Month
trace1=go.Bar(
   x=list(data.month.unique()),
   y=data[data.y=='yes'].month.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.month.unique()),
   y=data[data.y=='no'].month.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT POSSIBILITIES OF PREVIOUS CONTACT MONTH",
                 barmode='group',
                 xaxis=dict(title='Last contact month of year',
                            titlefont=dict(family='Calibri',size=16),
                            categoryorder='category ascending'),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [53]:
##Previous Contact Day
trace1=go.Bar(
   x=list(data.day_of_week.unique()),
   y=data[data.y=='yes'].day_of_week.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.day_of_week.unique()),
   y=data[data.y=='no'].day_of_week.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="NUMBER OF INSTANCES OF DIFFERENT POSSIBILITIES OF PREVIOUS CONTACT DAY",
                 barmode='group',
                 xaxis=dict(title='Last contact day of week',
                            titlefont=dict(family='Calibri',size=16),
                            categoryorder='category ascending'),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')

In [54]:
##Outcome of Previous Marketing Campaign
trace1=go.Bar(
   x=list(data.poutcome.unique()),
   y=data[data.y=='yes'].poutcome.value_counts().values,
   name='YES')

trace2=go.Bar(
   x=list(data.poutcome.unique()),
   y=data[data.y=='no'].poutcome.value_counts().values,
   name='NO')

temp_dat=[trace1,trace2]

layout=go.Layout(title="OUTCOME OF PREVIOUS MARKETING CAMPAIGN",
                 barmode='group',
                 xaxis=dict(title='Outcome of previous marketing campaign',
                            titlefont=dict(family='Calibri',size=16),
                            categoryorder='category ascending'),
                 yaxis=dict(title='Count',
                            titlefont=dict(family='Calibri',size=16))
                )
fig=go.Figure(data=temp_dat,layout=layout)

py.iplot(fig, filename='grouped-bar')